---
title: "Quickstart to arcpy"
author: "Michael Koohafkan"
date: "2020-08-05"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quickstart}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


```r
knitr::opts_chunk$set(echo = TRUE)
```

Getting started with `arcpy` in R is easy. Use the `use_ArcGIS()` 
function to connect to an ArcGIS installation. If you don't specify
a path, `arcpy` will search in the standard installation folders.
ArcGIS Desktop provides a stand-alone python installation while
ArcGIS Pro provides support for Conda virtual environments.


```r
library(arcpy)
```

The `arcpy` package can look for ArcGIS installations in their
default locations. 


```r
# Search for the default ArcGIS Pro Conda Python 3.x environment
find_ArcGIS(pro = TRUE)
```

```
## [1] "C:/Users/mkoohafk/AppData/Local/ESRI/conda/envs/arcgispro-py3-clone"
```

```r
# use the default ArcGIS Pro Conda Python 3.x environment
use_ArcGIS(pro = TRUE)
```

```
## Connected to ArcGISPro version 2.5.1 (build 22081).
```

The `arcpy` package automatically provides a `reticulate` module object 
called `arcpy`. This object provides the interface to ArcGIS.


```r
arcpy
```

```
## Module(arcpy)
```

```r
arcpy$GetInstallInfo()$ProductName
```

```
## [1] "ArcGISPro"
```

Once you are connected to your ArcGIS installation, using `arcpy` functions
and classes is as seamless as using any other Python module via `reticulate`.
The `arcpy` pacakge also re-exports reticulate's `py_help` function so that 
you can access the `arcpy` documentation.



```r
# get and set the arcpy environment
arcpy$env$workspace = tempdir()
arcpy$env$workspace
```

```
## [1] "C:\\Users\\mkoohafk\\AppData\\Local\\Temp\\Rtmp6ZWhiE"
```

```r
# get help on arcpy functions
py_help(arcpy$Exists)
```

Happy scripting!
